#!/bin/bash

curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | bash

for PKG in /vagrant/results/*.hart; do 
  hab pkg install $PKG
done

id hab &>/dev/null || useradd hab

# Disable ipv6 so --listen-gossip and --listen-http can use ipv4
if [[ $(cat /proc/sys/net/ipv6/conf/all/disable_ipv6) == "0" ]]; then 
  echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
  service networking restart
fi
